[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/accord/**"]

[[redirects]]
  from = "/api/verdict"
  to = "/.netlify/functions/verdict"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
